<?php

namespace RuralBundle\Repository;

/**
 * AlojamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlojamientoRepository extends \Doctrine\ORM\EntityRepository
{
}
